# Generated by Django 4.0 on 2022-07-23 14:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название категории')),
                ('level', models.IntegerField(verbose_name='Уровень')),
                ('slug', models.SlugField(max_length=255)),
                ('road', models.CharField(max_length=500, verbose_name='Путь')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона')),
                ('message', models.TextField(max_length=500, verbose_name='Сообщение')),
                ('email', models.EmailField(max_length=200)),
                ('type_site', models.CharField(choices=[('Интернет магазин', 'Интернет магазин'), ('Лендинг', 'Лендинг'), ('Корпаративный сайт', 'Корпаративный сайт'), ('Образовательная платформа', 'Образовательная платформа'), ('Другое', 'Другое')], max_length=255, verbose_name='Тип сайта')),
                ('created', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время отправления')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('phone', models.CharField(blank=True, default='8xxxxxxxxxx', max_length=11, null=True, verbose_name='номер телефона')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/users/%Y/%m/%d/', verbose_name='Ваше фото')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания профиля')),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата последнего редактирования профиля')),
                ('role', models.CharField(blank=True, choices=[('Backcend developer', 'Backcend developer'), ('Frontend developer', 'Frontend developer'), ('Fullstack developer', 'Fullstack developer'), ('Designer', 'Designer'), ('Seo', 'Seo')], max_length=100, null=True, verbose_name='Роль')),
                ('scrum_master', models.BooleanField(default=False, verbose_name='Скрам мастер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/projects/%Y/%m/%d/', verbose_name='Изображание связанное с проектом')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость проекта')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название комады')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последних изменений')),
                ('members', models.ManyToManyField(blank=True, null=True, to='mainapp.Profile', verbose_name='Члены команды')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.project', verbose_name='Текущий проект')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок статьи')),
                ('slug', models.SlugField(max_length=255)),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('update', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего редактирования')),
                ('road', models.CharField(max_length=700, verbose_name='Путь')),
                ('is_private', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to='auth.user')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
