# Generated by Django 4.0 on 2022-06-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона')),
                ('message', models.TextField(max_length=500, verbose_name='Сообщение')),
                ('email', models.EmailField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время отправления')),
            ],
        ),
    ]
